config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  devise_scope :user do
    # get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_in/:provider', :to => redirect('/users/auth/%{provider}'), :as => :sign_in
    get 'sign_out', :to => 'users/sessions#destroy', :as => :sign_out
  end

  resources :groups

  resources :themes do
    resources :items, shallow: true do
      resources :reviews
    end
  end

  resources :users

  namespace :api, format: :json do
    resources :themes, only: %i(index show create update destroy) do
      resources :items, only: %i(index show create update destroy), shallow: true do
        resources :reviews, only: %i(index show create update destroy), shallow: true
      end
    end

    resources :groups, only: %i(index show create update destroy)

    # 自分の
    resource :account, only: [] do
      scope module: 'account' do
        resources :groups, only: %i(index)
      end
    end
  end

  root to: 'pages#root'
end

app/models/theme.rb
# == Schema Information
#
# Table name: themes
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  private    :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  group_id   :integer
#  creator_id :integer
#
# Indexes
#
#  index_themes_on_group_id  (group_id)
#

class Theme < ActiveRecord::Base
  belongs_to :creator, class_name: :User
  belongs_to :group
  has_many :items

  validates :name,
    presence: true


  def editable?(user)
    return false unless user
    return true if creator && creator == user
    return true if group && group.users && group.users.exists?(id: user.id)
    false
  end
end

app/controllers/api/themes_controller.rb
class Api::ThemesController < Api::ApplicationController
  before_action :authenticate_user!, only: %i(create update destroy)
  before_action :set_theme, only: %i(show update destroy)
  before_action :check_editable, only: %i(update destroy)

  # GET /api/themes
  def index
    @themes = Theme.all
  end

  # GET /api/themes/1
  validates :show do
    integer :id, required: true
  end
  def show
  end

  # POST /api/themes
  validates :create do
    object :theme, required: true do
      string :name, strong: true, required: true
      boolean :private, strong: true
      integer :group_id, strong: true
    end
  end
  def create
    @theme = Theme.new(theme_params.merge creator: current_user)

    if @theme.save
      render :show, status: :created
    else
      render json: @theme.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /api/themes/1
  validates :update do
    integer :id, required: true
    object :theme, required: true do
      string :name, strong: true
      boolean :private, strong: true
      integer :group_id, strong: true
    end
  end
  def update
    if @theme.update(theme_params)
      render :show, status: :ok
    else
      render json: @theme.errors, status: :unprocessable_entity
    end
  end

  # DELETE /api/themes/1
  validates :destroy do
    integer :id, required: true
  end
  def destroy
    @theme.destroy
    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def theme_params
      permitted_params[:theme]
    end

    def check_editable
      forbidden 'You cannot edit this theme.' unless @theme.editable?(current_user)
    end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  # GET /themes
  def index
    @themes = Theme.all
  end

  # GET /themes/1
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes
  def create
    @theme = Theme.new(theme_params)

    if @theme.save
      redirect_to @theme, notice: 'Theme was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /themes/1
  def update
    if @theme.update(theme_params)
      redirect_to @theme, notice: 'Theme was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /themes/1
  def destroy
    @theme.destroy
    redirect_to themes_url, notice: 'Theme was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def theme_params
      params.require(:theme).permit(:name, :private)
    end
end

app/views/themes/_form.html.slim
= form_for @theme do |f|
  - if @theme.errors.any?
    #error_explanation
      h2 = "#{pluralize(@theme.errors.count, "error")} prohibited this theme from being saved:"
      ul
        - @theme.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :private
    = f.check_box :private
  .actions = f.submit

app/views/themes/edit.html.slim
h1 Editing theme

== render 'form'

= link_to 'Show', @theme
'|
= link_to 'Back', themes_path

app/views/themes/index.html.slim
h1 Listing themes

h2 html

table
  thead
    tr
      th Name
      th Private
      th
      th
      th

  tbody
    - @themes.each do |theme|
      tr
        td = theme.name
        td = theme.private
        td = link_to 'Show', theme
        td = link_to 'Edit', edit_theme_path(theme)
        td = link_to 'Destroy', theme, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Theme', new_theme_path

app/views/themes/new.html.slim
h1 New theme

== render 'form'

= link_to 'Back', themes_path

app/views/themes/show.html.slim
p#notice = notice

p
  strong Name:
  = @theme.name
p
  strong Private:
  = @theme.private

= link_to 'Edit', edit_theme_path(@theme)
'|
= link_to 'Back', themes_path