config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  devise_scope :user do
    # get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_in/:provider', :to => redirect('/users/auth/%{provider}'), :as => :sign_in
    get 'sign_out', :to => 'users/sessions#destroy', :as => :sign_out
  end

  resources :groups

  resources :themes do
    resources :items, shallow: true do
      resources :reviews
    end
  end

  resources :users

  namespace :api, format: :json do
    resources :themes, only: %i(index show create update destroy) do
      resources :items, only: %i(index show create update destroy), shallow: true do
        resources :reviews, only: %i(index show create update destroy), shallow: true
      end
    end

    resources :groups, only: %i(index show create update destroy)

    # 自分の
    resource :account, only: [] do
      scope module: 'account' do
        resources :groups, only: %i(index)
      end
    end
  end

  root to: 'pages#root'
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id          :integer          not null, primary key
#  name        :string           not null
#  description :text             not null
#  theme_id    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_items_on_theme_id  (theme_id)
#

class Item < ActiveRecord::Base
  belongs_to :theme
  has_many :reviews

  validates :name,
    presence: true
end

app/controllers/api/items_controller.rb
class Api::ItemsController < Api::ApplicationController
  before_action :authenticate_user!, only: %i(create update destroy)
  before_action :set_item, only: %i(show update destroy)
  before_action :set_theme
  before_action :check_editable, only: %i(create update destroy)

  # GET /api/themes/:theme_id/items
  validates :index do
    integer :theme_id, required: true
  end
  def index
    @items = @theme.items
  end

  # GET /api/items/:id
  validates :show do
    integer :id, required: true
  end
  def show
  end

  # POST /api/themes/:theme_id/items
  validates :create do
    integer :theme_id, required: true
    object :item, required: true do
      string :name, strong: true, required: true
      string :description, strong: true
    end
  end
  def create
    @item = @theme.items.new(item_params)

    if @item.save
      render :show, status: :created
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end

  # PATCH /api/items/:id
  validates :update do
    integer :id, required: true
    object :item, required: true do
      string :name, strong: true
      string :description, strong: true
    end
  end
  def update
    if @item.update(item_params)
      render :show, status: :ok
    else
      render json: @item.errors, status: :unprocessable_entity
    end
  end

  # DELETE /api/items/:id
  validates :destroy do
    integer :id, required: true
  end
  def destroy
    @item.destroy
    head :no_content
  end

  private

    def set_item
      @item = Item.find(params[:id])
    end

    def set_theme
      @theme = @item ? @item.theme : Theme.find(params[:theme_id])
    end

    def check_editable
      forbidden 'You cannot edit this item.'  unless @theme.editable?(current_user)
    end

    def item_params
      permitted_params[:item]
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_theme

  # GET /themes/10/items
  def index
    @items = Item.all
  end

  # GET /items/1
  def show
  end

  # GET /themes/10/items/new
  def new
    @item = Item.new(theme: @theme)
  end

  # GET /items/1/edit
  def edit
  end

  # POST /themes/10/items
  def create
    @item = Item.new(item_params.merge theme: @theme)

    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to theme_items_url(@theme), notice: 'Item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def set_theme
      @theme = @item ? @item.theme : Theme.find(params[:theme_id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:name, :description)
    end
end

app/views/items/_form.html.slim
= form_for @item do |f|
  - if @item.errors.any?
    #error_explanation
      h2 = "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      ul
        - @item.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :theme
    = f.text_field :theme
  .actions = f.submit

app/views/items/edit.html.slim
h1 Editing item

== render 'form'

= link_to 'Show', @item
'|
= link_to 'Back', theme_items_path(@theme)

app/views/items/index.html.slim
h1 Listing items

table
  thead
    tr
      th Name
      th Description
      th Theme
      th
      th
      th

  tbody
    - @items.each do |item|
      tr
        td = item.name
        td = item.description
        td = item.theme
        td = link_to 'Show', item
        td = link_to 'Edit', edit_item_path(item)
        td = link_to 'Destroy', item, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Item', new_theme_item_path(@theme)

app/views/items/new.html.slim
h1 New item

== render 'form'

= link_to 'Back', theme_items_path(@theme)

app/views/items/show.html.slim
p#notice = notice

p
  strong Name:
  = @item.name
p
  strong Description:
  = @item.description
p
  strong Theme:
  = @item.theme

= link_to 'Edit', edit_item_path(@item)
'|
= link_to 'Back', theme_items_path(@theme)